import './morse-test/morse-letter.imba'
import './morse-test/morse-word.imba'
import './morse-test/morse-words-example.imba'

import './hangman/hangman.imba'
import './hangman/hangman-word.imba'
import './hangman/hangman-letter.imba'
import './hangman/hangman-mistakes.imba'
import './hangman/hangman-options.imba'
import './hangman/hangman-option.imba'
import './hangman/hangman-result.imba'
import './hangman/hangman-replay.imba'