import './morse-test/morse-letter.imba'
import './morse-test/morse-word.imba'
import './morse-test/morse-words-example.imba'

import './hangman-test/hangman-game.imba'
import './hangman-test/hangman-word.imba'
import './hangman-test/hangman-letter.imba'
import './hangman-test/hangman-options.imba'
import './hangman-test/hangman-option.imba'
import './hangman-test/hangman-mistakes.imba'
import './hangman-test/hangman-message.imba'